In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [2]:
clean_health_dataset=pd.read_csv('clean_health_dataset.csv')
clean_health_dataset.head(20)

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
0,Female,No,Moderate,Never,Normal,Borderline,High,90.0,16.6,119.0,3.6,143.6,Occasional,No,Yes
1,Other,Yes,Moderate,Never,Normal,Normal,Low,20.0,29.9,69.0,9.9,121.8,Occasional,Yes,No
2,Male,Yes,Heavy,Daily,High,High,Low,52.0,33.5,54.0,8.5,107.0,Occasional,Yes,Yes
3,Male,Yes,Heavy,Daily,Normal,High,Low,15.0,20.3,72.0,9.5,92.1,Occasional,No,Yes
4,Male,No,Moderate,Often,High,High,Medium,60.0,36.0,58.0,4.4,113.6,Occasional,No,Yes
5,Male,No,Moderate,Daily,Low,High,High,53.0,15.8,107.0,9.7,149.0,Occasional,No,No
6,Male,Yes,Moderate,Daily,Low,Borderline,Low,39.0,36.1,108.0,4.0,144.9,Occasional,Yes,Yes
7,Male,No,Moderate,Daily,Normal,Borderline,High,25.0,26.5,103.0,6.6,91.3,Occasional,Yes,Yes
8,Male,No,Moderate,Never,High,Borderline,Medium,79.0,20.4,95.0,8.8,86.2,Occasional,No,Yes
9,Female,Yes,Moderate,Never,High,High,Medium,91.0,18.3,71.0,5.4,73.5,Regular,No,No
10,Other,Yes,Moderate,Never,Low,Borderline,Low,64.0,38.8,113.0,6.0,71.6,Occasional,Yes,Yes
11,Male,No,Moderate,Daily,Low,Borderline,Low,99.0,16.8,57.0,3.9,184.4,Regular,No,Yes
12,Female,Yes,Moderate,Never,High,Normal,High,73.0,20.0,69.0,3.9,75.9,Occasional,No,Yes
13,Female,No,Heavy,Daily,Normal,Normal,Low,63.0,23.7,100.0,7.3,165.1,Occasional,Yes,Yes
14,Other,No,Moderate,Never,Low,Borderline,High,42.0,30.5,88.0,7.7,183.4,Regular,No,No
15,Male,No,Moderate,Never,Normal,Normal,Low,16.0,28.6,86.0,8.4,82.7,Occasional,Yes,Yes
16,Other,No,Moderate,Rarely,Normal,Normal,High,58.0,18.1,99.0,6.9,126.7,Regular,Yes,No
17,Male,No,Moderate,Often,Low,Borderline,High,22.0,22.2,83.0,7.5,195.1,Regular,Yes,No
18,Female,Yes,Moderate,Daily,Normal,Borderline,High,6.0,21.0,82.0,3.1,178.4,Occasional,No,No
19,Female,Yes,Moderate,Rarely,Normal,Borderline,High,43.0,20.3,80.0,4.1,133.7,Occasional,No,Yes

In [4]:
clean_health_dataset=pd.read_csv('clean_health_dataset.csv')
clean_health_dataset.tail(20)

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
980,Other,Yes,Moderate,Daily,Low,Normal,Low,50.0,24.9,82.000000,9.6,187.5,Occasional,No,No
981,Male,Yes,Moderate,Never,Normal,Normal,High,56.0,20.0,60.000000,9.5,148.3,Occasional,Yes,No
982,Female,Yes,Moderate,Rarely,Normal,High,Medium,94.0,25.6,69.000000,5.7,134.1,Occasional,No,No
983,Female,Yes,Moderate,Daily,High,High,Medium,11.0,24.6,73.000000,3.6,172.1,Occasional,No,Yes
984,Male,Yes,Moderate,Rarely,High,High,High,4.0,37.9,113.000000,4.2,193.2,Occasional,Yes,No
985,Other,No,Moderate,Daily,High,Borderline,High,49.0,34.0,114.000000,3.4,116.3,Occasional,Yes,No
986,Male,No,Heavy,Daily,Low,High,High,41.0,27.6,66.000000,3.7,102.5,Occasional,No,No
987,Male,No,Heavy,Often,Normal,High,Low,11.0,39.7,110.000000,4.3,150.1,Occasional,Yes,No
988,Other,No,Heavy,Rarely,Low,Normal,Medium,17.0,26.6,64.000000,5.4,134.9,Occasional,No,No
989,Other,Yes,Heavy,Never,Normal,Normal,High,65.0,16.5,100.000000,6.8,198.6,Regular,Yes,No
990,Female,Yes,Moderate,Often,Low,High,Medium,73.0,21.6,76.000000,8.0,130.1,Regular,No,No
991,Other,No,Heavy,Often,High,High,Low,78.0,25.9,110.000000,4.5,79.7,Occasional,Yes,No
992,Female,No,Moderate,Never,High,Normal,Low,93.0,18.9,107.000000,7.7,197.1,Occasional,Yes,No
993,Other,Yes,Heavy,Often,High,High,Low,16.0,38.7,80.000000,7.9,179.7,Occasional,Yes,No
994,Male,No,Moderate,Daily,Low,Borderline,Low,67.0,34.2,61.000000,6.9,93.2,Regular,Yes,No
995,Female,No,Heavy,Daily,Normal,Borderline,Medium,70.0,21.7,95.000000,9.3,187.6,Regular,No,Yes
996,Female,No,Heavy,Rarely,Normal,Borderline,Low,61.0,29.8,80.000000,3.8,114.3,Regular,Yes,Yes
997,Female,No,Moderate,Rarely,Normal,High,Low,40.0,33.0,81.000000,4.2,119.0,Regular,No,No
998,Male,Yes,Heavy,Never,High,Normal,High,94.0,38.5,81.000000,6.0,187.8,Occasional,Yes,No
999,Male,No,Moderate,Rarely,High,High,Low,33.0,37.0,85.076613,3.9,138.9,Occasional,Yes,Yes

In [5]:
clean_health_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gender               1000 non-null   str
 1   Smoking              1000 non-null   str
 2   Alcohol_Consumption  1000 non-null   str
 3   Exercise_Frequency   1000 non-null   str
 4   Blood_Pressure       1000 non-null   str
 5   Cholesterol_Level    1000 non-null   str
 6   Stress_Level         1000 non-null   str
 7   Age                  1000 non-null   float64
 8   BMI                  1000 non-null   float64
 9   Heart_Rate           1000 non-null   float64
 10  Sleep_Hours          1000 non-null   float64
 11  Blood_Sugar_Level    1000 non-null   float64
 12  Medication_Use       1000 non-null   str
 13  Family_History       1000 non-null   str
 14  Illness              1000 non-null   str
dtypes: float64(5), str(10)
memory usage: 117.3 KB

In [6]:
clean_health_dataset.isna()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:
#check null value 
clean_health_dataset.isna().sum()

Gender                 0
Smoking                0
Alcohol_Consumption    0
Exercise_Frequency     0
Blood_Pressure         0
Cholesterol_Level      0
Stress_Level           0
Age                    0
BMI                    0
Heart_Rate             0
Sleep_Hours            0
Blood_Sugar_Level      0
Medication_Use         0
Family_History         0
Illness                0
dtype: int64

In [10]:
#check duplicate value 
clean_health_dataset.duplicated().sum()

np.int64(0)

In [11]:
#numeric column describe 
clean_health_dataset.describe()

               Age          BMI   Heart_Rate  Sleep_Hours  Blood_Sugar_Level
count  1000.000000  1000.000000  1000.000000  1000.000000        1000.000000
mean     49.545000    27.408048    85.076613     6.588632         135.665000
std      28.692285     7.216897    20.155903     2.031790          37.089282
min       0.000000    15.100000    50.000000     3.000000          70.200000
25%      24.000000    21.100000    68.000000     4.800000         104.600000
50%      50.000000    27.404024    85.000000     6.600000         136.300000
75%      75.000000    33.600000   103.000000     8.400000         168.700000
max      99.000000    40.000000   119.000000    10.000000         200.000000

In [12]:
# copy dataset
clean_health_dataset_1=clean_health_dataset.copy()
clean_health_dataset_2=clean_health_dataset.copy() 
clean_health_dataset_3=clean_health_dataset.copy() 
clean_health_dataset_4=clean_health_dataset.copy()
clean_health_dataset_5=clean_health_dataset.copy() 
clean_health_dataset_6=clean_health_dataset.copy()  
clean_health_dataset_7=clean_health_dataset.copy()
clean_health_dataset_8=clean_health_dataset.copy() 
clean_health_dataset_9=clean_health_dataset.copy()  
clean_health_dataset_10=clean_health_dataset.copy()

In [15]:
print(clean_health_dataset_1)

     Gender Smoking Alcohol_Consumption Exercise_Frequency Blood_Pressure  \
0    Female      No            Moderate              Never         Normal
1     Other     Yes            Moderate              Never         Normal
2      Male     Yes               Heavy              Daily           High
3      Male     Yes               Heavy              Daily         Normal
4      Male      No            Moderate              Often           High
..      ...     ...                 ...                ...            ...
995  Female      No               Heavy              Daily         Normal
996  Female      No               Heavy             Rarely         Normal
997  Female      No            Moderate             Rarely         Normal
998    Male     Yes               Heavy              Never           High
999    Male      No            Moderate             Rarely           High

    Cholesterol_Level Stress_Level   Age   BMI  Heart_Rate  Sleep_Hours  \
0          Borderline         High  90.0  16.6  119.000000          3.6
1              Normal          Low  20.0  29.9   69.000000          9.9
2                High          Low  52.0  33.5   54.000000          8.5
3                High          Low  15.0  20.3   72.000000          9.5
4                High       Medium  60.0  36.0   58.000000          4.4
..                ...          ...   ...   ...         ...          ...
995        Borderline       Medium  70.0  21.7   95.000000          9.3
996        Borderline          Low  61.0  29.8   80.000000          3.8
997              High          Low  40.0  33.0   81.000000          4.2
998            Normal         High  94.0  38.5   81.000000          6.0
999              High          Low  33.0  37.0   85.076613          3.9

     Blood_Sugar_Level Medication_Use Family_History Illness
0                143.6     Occasional             No     Yes
1                121.8     Occasional            Yes      No
2                107.0     Occasional            Yes     Yes
3                 92.1     Occasional             No     Yes
4                113.6     Occasional             No     Yes
..                 ...            ...            ...     ...
995              187.6        Regular             No     Yes
996              114.3        Regular            Yes     Yes
997              119.0        Regular             No      No
998              187.8     Occasional            Yes      No
999              138.9     Occasional            Yes     Yes

[1000 rows x 15 columns]

In [13]:
#show not fitted
le

LabelEncoder()

In [17]:
#using loop for fit and transform 
#encoding is not applicable for numeric data 

from pandas.api.types import is_numeric_dtype   #import method for check numeric or not 
for col in clean_health_dataset_1.columns: 
    if is_numeric_dtype(clean_health_dataset_1[col]):   #is_numeric_dtype ekti method  numeric kina check korar
        continue
    else: 
        clean_health_dataset_1[col] = le.fit_transform(clean_health_dataset_1[col])

In [19]:
#now my dataset is encoded 
clean_health_dataset_1.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
0,0,0,1,1,2,0,0,90.0,16.6,119.0,3.6,143.6,0,0,1
1,2,1,1,1,2,2,1,20.0,29.9,69.0,9.9,121.8,0,1,0
2,1,1,0,0,0,1,1,52.0,33.5,54.0,8.5,107.0,0,1,1
3,1,1,0,0,2,1,1,15.0,20.3,72.0,9.5,92.1,0,0,1
4,1,0,1,2,0,1,2,60.0,36.0,58.0,4.4,113.6,0,0,1

In [21]:
#check correalation 
clean_health_dataset_1.corr()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
Gender,1.000000,-0.004957,0.037390,-0.050383,0.019782,-0.036862,-0.042099,-0.041500,0.090002,-0.028893,-0.022740,-0.003631,0.018744,0.064432,-0.054502
Smoking,-0.004957,1.000000,-0.007859,-0.014245,0.009048,0.000017,-0.019171,-0.005320,0.034020,-0.046145,0.021746,-0.015045,-0.016139,-0.015104,-0.026701
Alcohol_Consumption,0.037390,-0.007859,1.000000,-0.033896,-0.022469,0.021190,-0.018848,0.034559,-0.051959,-0.005890,0.013873,0.012777,0.023454,-0.028083,0.018852
Exercise_Frequency,-0.050383,-0.014245,-0.033896,1.000000,0.010975,-0.011367,0.029628,-0.035765,0.010384,-0.013763,0.011416,0.023647,-0.012080,-0.038627,-0.022100
Blood_Pressure,0.019782,0.009048,-0.022469,0.010975,1.000000,0.007863,-0.032936,0.038226,-0.011531,-0.000454,-0.020047,-0.056630,-0.022316,-0.013178,0.013272
Cholesterol_Level,-0.036862,0.000017,0.021190,-0.011367,0.007863,1.000000,0.017064,0.038696,-0.020679,-0.042331,-0.022940,0.021531,-0.021479,-0.017282,0.010445
Stress_Level,-0.042099,-0.019171,-0.018848,0.029628,-0.032936,0.017064,1.000000,-0.009079,-0.007865,-0.025102,0.060456,-0.034823,-0.046909,0.051337,0.022513
Age,-0.041500,-0.005320,0.034559,-0.035765,0.038226,0.038696,-0.009079,1.000000,-0.018398,-0.008679,-0.034592,-0.047938,0.004904,-0.042897,0.022039
BMI,0.090002,0.034020,-0.051959,0.010384,-0.011531,-0.020679,-0.007865,-0.018398,1.000000,-0.021817,0.006506,0.032426,0.026235,0.037204,0.046642
Heart_Rate,-0.028893,-0.046145,-0.005890,-0.013763,-0.000454,-0.042331,-0.025102,-0.008679,-0.021817,1.000000,-0.008783,-0.022406,-0.018838,0.044911,0.039390
Sleep_Hours,-0.022740,0.021746,0.013873,0.011416,-0.020047,-0.022940,0.060456,-0.034592,0.006506,-0.008783,1.000000,-0.010416,-0.040871,-0.036391,0.005268
Blood_Sugar_Level,-0.003631,-0.015045,0.012777,0.023647,-0.056630,0.021531,-0.034823,-0.047938,0.032426,-0.022406,-0.010416,1.000000,-0.030070,-0.034868,0.021042
Medication_Use,0.018744,-0.016139,0.023454,-0.012080,-0.022316,-0.021479,-0.046909,0.004904,0.026235,-0.018838,-0.040871,-0.030070,1.000000,-0.030459,-0.038495
Family_History,0.064432,-0.015104,-0.028083,-0.038627,-0.013178,-0.017282,0.051337,-0.042897,0.037204,0.044911,-0.036391,-0.034868,-0.030459,1.000000,0.035385
Illness,-0.054502,-0.026701,0.018852,-0.022100,0.013272,0.010445,0.022513,0.022039,0.046642,0.039390,0.005268,0.021042,-0.038495,0.035385,1.000000

In [23]:
#now its show fitted
le

LabelEncoder()

# Feature Transformation

In [ ]:
# it is use for numeric value convert into 0-1 range.ot help for data linear relationship
#all column is feature without target columna
#target column data is plasma level 

# first :for target column need those column that is called feature selection 
#second: if need to create new feature for target column called feature extraction
# third:encoding 
#fourth: transformation

# if i need i can convert 2 feature to 100 and 100 to 2 
# there are many kind of feature transformation technuque 
#it is not applicable for only target column