In [1]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder

In [2]:
clean_health_dataset=pd.read_csv('clean_health_dataset.csv')
clean_health_dataset.head(20)

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
0,Female,No,Moderate,Never,Normal,Borderline,High,90.0,16.6,119.0,3.6,143.6,Occasional,No,Yes
1,Other,Yes,Moderate,Never,Normal,Normal,Low,20.0,29.9,69.0,9.9,121.8,Occasional,Yes,No
2,Male,Yes,Heavy,Daily,High,High,Low,52.0,33.5,54.0,8.5,107.0,Occasional,Yes,Yes
3,Male,Yes,Heavy,Daily,Normal,High,Low,15.0,20.3,72.0,9.5,92.1,Occasional,No,Yes
4,Male,No,Moderate,Often,High,High,Medium,60.0,36.0,58.0,4.4,113.6,Occasional,No,Yes
5,Male,No,Moderate,Daily,Low,High,High,53.0,15.8,107.0,9.7,149.0,Occasional,No,No
6,Male,Yes,Moderate,Daily,Low,Borderline,Low,39.0,36.1,108.0,4.0,144.9,Occasional,Yes,Yes
7,Male,No,Moderate,Daily,Normal,Borderline,High,25.0,26.5,103.0,6.6,91.3,Occasional,Yes,Yes
8,Male,No,Moderate,Never,High,Borderline,Medium,79.0,20.4,95.0,8.8,86.2,Occasional,No,Yes
9,Female,Yes,Moderate,Never,High,High,Medium,91.0,18.3,71.0,5.4,73.5,Regular,No,No
10,Other,Yes,Moderate,Never,Low,Borderline,Low,64.0,38.8,113.0,6.0,71.6,Occasional,Yes,Yes
11,Male,No,Moderate,Daily,Low,Borderline,Low,99.0,16.8,57.0,3.9,184.4,Regular,No,Yes
12,Female,Yes,Moderate,Never,High,Normal,High,73.0,20.0,69.0,3.9,75.9,Occasional,No,Yes
13,Female,No,Heavy,Daily,Normal,Normal,Low,63.0,23.7,100.0,7.3,165.1,Occasional,Yes,Yes
14,Other,No,Moderate,Never,Low,Borderline,High,42.0,30.5,88.0,7.7,183.4,Regular,No,No
15,Male,No,Moderate,Never,Normal,Normal,Low,16.0,28.6,86.0,8.4,82.7,Occasional,Yes,Yes
16,Other,No,Moderate,Rarely,Normal,Normal,High,58.0,18.1,99.0,6.9,126.7,Regular,Yes,No
17,Male,No,Moderate,Often,Low,Borderline,High,22.0,22.2,83.0,7.5,195.1,Regular,Yes,No
18,Female,Yes,Moderate,Daily,Normal,Borderline,High,6.0,21.0,82.0,3.1,178.4,Occasional,No,No
19,Female,Yes,Moderate,Rarely,Normal,Borderline,High,43.0,20.3,80.0,4.1,133.7,Occasional,No,Yes

In [3]:
clean_health_dataset=pd.read_csv('clean_health_dataset.csv')
clean_health_dataset.tail(20)

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness
980,Other,Yes,Moderate,Daily,Low,Normal,Low,50.0,24.9,82.000000,9.6,187.5,Occasional,No,No
981,Male,Yes,Moderate,Never,Normal,Normal,High,56.0,20.0,60.000000,9.5,148.3,Occasional,Yes,No
982,Female,Yes,Moderate,Rarely,Normal,High,Medium,94.0,25.6,69.000000,5.7,134.1,Occasional,No,No
983,Female,Yes,Moderate,Daily,High,High,Medium,11.0,24.6,73.000000,3.6,172.1,Occasional,No,Yes
984,Male,Yes,Moderate,Rarely,High,High,High,4.0,37.9,113.000000,4.2,193.2,Occasional,Yes,No
985,Other,No,Moderate,Daily,High,Borderline,High,49.0,34.0,114.000000,3.4,116.3,Occasional,Yes,No
986,Male,No,Heavy,Daily,Low,High,High,41.0,27.6,66.000000,3.7,102.5,Occasional,No,No
987,Male,No,Heavy,Often,Normal,High,Low,11.0,39.7,110.000000,4.3,150.1,Occasional,Yes,No
988,Other,No,Heavy,Rarely,Low,Normal,Medium,17.0,26.6,64.000000,5.4,134.9,Occasional,No,No
989,Other,Yes,Heavy,Never,Normal,Normal,High,65.0,16.5,100.000000,6.8,198.6,Regular,Yes,No
990,Female,Yes,Moderate,Often,Low,High,Medium,73.0,21.6,76.000000,8.0,130.1,Regular,No,No
991,Other,No,Heavy,Often,High,High,Low,78.0,25.9,110.000000,4.5,79.7,Occasional,Yes,No
992,Female,No,Moderate,Never,High,Normal,Low,93.0,18.9,107.000000,7.7,197.1,Occasional,Yes,No
993,Other,Yes,Heavy,Often,High,High,Low,16.0,38.7,80.000000,7.9,179.7,Occasional,Yes,No
994,Male,No,Moderate,Daily,Low,Borderline,Low,67.0,34.2,61.000000,6.9,93.2,Regular,Yes,No
995,Female,No,Heavy,Daily,Normal,Borderline,Medium,70.0,21.7,95.000000,9.3,187.6,Regular,No,Yes
996,Female,No,Heavy,Rarely,Normal,Borderline,Low,61.0,29.8,80.000000,3.8,114.3,Regular,Yes,Yes
997,Female,No,Moderate,Rarely,Normal,High,Low,40.0,33.0,81.000000,4.2,119.0,Regular,No,No
998,Male,Yes,Heavy,Never,High,Normal,High,94.0,38.5,81.000000,6.0,187.8,Occasional,Yes,No
999,Male,No,Moderate,Rarely,High,High,Low,33.0,37.0,85.076613,3.9,138.9,Occasional,Yes,Yes

In [4]:
clean_health_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gender               1000 non-null   str
 1   Smoking              1000 non-null   str
 2   Alcohol_Consumption  1000 non-null   str
 3   Exercise_Frequency   1000 non-null   str
 4   Blood_Pressure       1000 non-null   str
 5   Cholesterol_Level    1000 non-null   str
 6   Stress_Level         1000 non-null   str
 7   Age                  1000 non-null   float64
 8   BMI                  1000 non-null   float64
 9   Heart_Rate           1000 non-null   float64
 10  Sleep_Hours          1000 non-null   float64
 11  Blood_Sugar_Level    1000 non-null   float64
 12  Medication_Use       1000 non-null   str
 13  Family_History       1000 non-null   str
 14  Illness              1000 non-null   str
dtypes: float64(5), str(10)
memory usage: 117.3 KB

In [5]:
#check null value 
clean_health_dataset.isna().sum()

Gender                 0
Smoking                0
Alcohol_Consumption    0
Exercise_Frequency     0
Blood_Pressure         0
Cholesterol_Level      0
Stress_Level           0
Age                    0
BMI                    0
Heart_Rate             0
Sleep_Hours            0
Blood_Sugar_Level      0
Medication_Use         0
Family_History         0
Illness                0
dtype: int64

In [6]:
#check duplicate value 
clean_health_dataset.duplicated().sum()

np.int64(0)

In [7]:
#numeric column describe 
clean_health_dataset.describe()

               Age          BMI   Heart_Rate  Sleep_Hours  Blood_Sugar_Level
count  1000.000000  1000.000000  1000.000000  1000.000000        1000.000000
mean     49.545000    27.408048    85.076613     6.588632         135.665000
std      28.692285     7.216897    20.155903     2.031790          37.089282
min       0.000000    15.100000    50.000000     3.000000          70.200000
25%      24.000000    21.100000    68.000000     4.800000         104.600000
50%      50.000000    27.404024    85.000000     6.600000         136.300000
75%      75.000000    33.600000   103.000000     8.400000         168.700000
max      99.000000    40.000000   119.000000    10.000000         200.000000

In [8]:
# copy dataset
clean_health_dataset_1=clean_health_dataset.copy()
clean_health_dataset_2=clean_health_dataset.copy() 
clean_health_dataset_3=clean_health_dataset.copy() 
clean_health_dataset_4=clean_health_dataset.copy()
clean_health_dataset_5=clean_health_dataset.copy() 
clean_health_dataset_6=clean_health_dataset.copy()  
clean_health_dataset_7=clean_health_dataset.copy()
clean_health_dataset_8=clean_health_dataset.copy() 
clean_health_dataset_9=clean_health_dataset.copy()  
clean_health_dataset_10=clean_health_dataset.copy()

In [9]:
print(clean_health_dataset_1)

     Gender Smoking Alcohol_Consumption Exercise_Frequency Blood_Pressure  \
0    Female      No            Moderate              Never         Normal
1     Other     Yes            Moderate              Never         Normal
2      Male     Yes               Heavy              Daily           High
3      Male     Yes               Heavy              Daily         Normal
4      Male      No            Moderate              Often           High
..      ...     ...                 ...                ...            ...
995  Female      No               Heavy              Daily         Normal
996  Female      No               Heavy             Rarely         Normal
997  Female      No            Moderate             Rarely         Normal
998    Male     Yes               Heavy              Never           High
999    Male      No            Moderate             Rarely           High

    Cholesterol_Level Stress_Level   Age   BMI  Heart_Rate  Sleep_Hours  \
0          Borderline         High  90.0  16.6  119.000000          3.6
1              Normal          Low  20.0  29.9   69.000000          9.9
2                High          Low  52.0  33.5   54.000000          8.5
3                High          Low  15.0  20.3   72.000000          9.5
4                High       Medium  60.0  36.0   58.000000          4.4
..                ...          ...   ...   ...         ...          ...
995        Borderline       Medium  70.0  21.7   95.000000          9.3
996        Borderline          Low  61.0  29.8   80.000000          3.8
997              High          Low  40.0  33.0   81.000000          4.2
998            Normal         High  94.0  38.5   81.000000          6.0
999              High          Low  33.0  37.0   85.076613          3.9

     Blood_Sugar_Level Medication_Use Family_History Illness
0                143.6     Occasional             No     Yes
1                121.8     Occasional            Yes      No
2                107.0     Occasional            Yes     Yes
3                 92.1     Occasional             No     Yes
4                113.6     Occasional             No     Yes
..                 ...            ...            ...     ...
995              187.6        Regular             No     Yes
996              114.3        Regular            Yes     Yes
997              119.0        Regular             No      No
998              187.8     Occasional            Yes      No
999              138.9     Occasional            Yes     Yes

[1000 rows x 15 columns]

In [11]:

ohe

sklearn.preprocessing._encoders.OneHotEncoder

In [12]:
#using loop for fit and transform 
#encoding is not applicable for numeric data 

from pandas.api.types import is_numeric_dtype   #import method for check numeric or not 
for col in clean_health_dataset_1.columns: 
    if is_numeric_dtype(clean_health_dataset_1[col]):   #is_numeric_dtype ekti method  numeric kina check korar
        continue
    else: 
        new_dummy=pd.get_dummies(clean_health_dataset_1[col],prefix=col).astype('float64')
        clean_health_dataset_1.drop([col],axis=1,inplace=True)
        clean_health_dataset_1=pd.concat([clean_health_dataset_1,new_dummy],axis=1)

In [13]:
clean_health_dataset_1.head()

,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Gender_Female,Gender_Male,Gender_Other,Smoking_No,Smoking_Yes,...,Cholesterol_Level_Normal,Stress_Level_High,Stress_Level_Low,Stress_Level_Medium,Medication_Use_Occasional,Medication_Use_Regular,Family_History_No,Family_History_Yes,Illness_No,Illness_Yes
0,90.0,16.6,119.0,3.6,143.6,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
1,20.0,29.9,69.0,9.9,121.8,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
2,52.0,33.5,54.0,8.5,107.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
3,15.0,20.3,72.0,9.5,92.1,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
4,60.0,36.0,58.0,4.4,113.6,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0

In [14]:
#check correlation
clean_health_dataset_1.corr()

,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Gender_Female,Gender_Male,Gender_Other,Smoking_No,Smoking_Yes,...,Cholesterol_Level_Normal,Stress_Level_High,Stress_Level_Low,Stress_Level_Medium,Medication_Use_Occasional,Medication_Use_Regular,Family_History_No,Family_History_Yes,Illness_No,Illness_Yes
Age,1.000000,-0.018398,-0.008679,-0.034592,-0.047938,0.051354,-0.030721,-0.020135,0.005320,-0.005320,...,0.074086,0.037969,-0.061615,0.022671,-0.004904,0.004904,0.042897,-0.042897,-0.022039,0.022039
BMI,-0.018398,1.000000,-0.021817,0.006506,0.032426,-0.101980,0.048143,0.053058,-0.034020,0.034020,...,-0.041864,0.009936,-0.006439,-0.003698,-0.026235,0.026235,-0.037204,0.037204,-0.046642,0.046642
Heart_Rate,-0.008679,-0.021817,1.000000,-0.008783,-0.022406,0.025857,-0.001913,-0.023914,0.046145,-0.046145,...,-0.052501,0.010243,0.023344,-0.033627,0.018838,-0.018838,-0.044911,0.044911,-0.039390,0.039390
Sleep_Hours,-0.034592,0.006506,-0.008783,1.000000,-0.010416,0.028439,-0.017424,-0.010733,-0.021746,0.021746,...,-0.028413,-0.056056,0.007951,0.049081,0.040871,-0.040871,0.036391,-0.036391,-0.005268,0.005268
Blood_Sugar_Level,-0.047938,0.032426,-0.022406,-0.010416,1.000000,0.008633,-0.010835,0.002377,0.015045,-0.015045,...,0.027645,0.039585,-0.019499,-0.020853,0.030070,-0.030070,0.034868,-0.034868,-0.021042,0.021042
Gender_Female,0.051354,-0.101980,0.025857,0.028439,0.008633,1.000000,-0.508095,-0.483680,-0.023660,0.023660,...,0.039699,-0.055541,-0.012091,0.068487,0.018728,-0.018728,0.046036,-0.046036,-0.035250,0.035250
Gender_Male,-0.030721,0.048143,-0.001913,-0.017424,-0.010835,-0.508095,1.000000,-0.508095,0.038163,-0.038163,...,-0.032780,0.047733,0.023797,-0.072190,-0.005084,0.005084,0.018618,-0.018618,-0.023014,0.023014
Gender_Other,-0.020135,0.053058,-0.023914,-0.010733,0.002377,-0.483680,-0.508095,1.000000,-0.015121,0.015121,...,-0.006388,0.007035,-0.012091,0.004871,-0.013561,0.013561,-0.064955,0.064955,0.058636,-0.058636
Smoking_No,0.005320,-0.034020,0.046145,-0.021746,0.015045,-0.023660,0.038163,-0.015121,1.000000,-1.000000,...,-0.025018,-0.018729,0.004471,0.014595,-0.016139,0.016139,-0.015104,0.015104,-0.026701,0.026701
Smoking_Yes,-0.005320,0.034020,-0.046145,0.021746,-0.015045,0.023660,-0.038163,0.015121,-1.000000,1.000000,...,0.025018,0.018729,-0.004471,-0.014595,0.016139,-0.016139,0.015104,-0.015104,0.026701,-0.026701
Alcohol_Consumption_Heavy,-0.034559,0.051959,0.005890,-0.013873,-0.012777,0.032029,0.000344,-0.032379,-0.007859,0.007859,...,-0.006257,-0.031009,0.030149,0.001543,0.023454,-0.023454,-0.028083,0.028083,0.018852,-0.018852
Alcohol_Consumption_Moderate,0.034559,-0.051959,-0.005890,0.013873,0.012777,-0.032029,-0.000344,0.032379,0.007859,-0.007859,...,0.006257,0.031009,-0.030149,-0.001543,-0.023454,0.023454,0.028083,-0.028083,-0.018852,0.018852
Exercise_Frequency_Daily,0.038987,0.017277,0.010274,-0.011951,0.014078,-0.004189,0.017967,-0.014069,-0.019537,0.019537,...,-0.005643,0.024025,-0.017896,-0.006629,0.009413,-0.009413,-0.009119,0.009119,-0.039281,0.039281
Exercise_Frequency_Never,0.020114,-0.022968,-0.006436,0.004241,-0.052518,-0.055058,-0.015317,0.070623,0.004512,-0.004512,...,0.017548,0.018918,-0.024582,0.005212,-0.033560,0.033560,-0.044162,0.044162,0.017451,-0.017451
Exercise_Frequency_Often,-0.066466,-0.031486,0.017586,-0.002056,0.004540,0.000751,0.003383,-0.004189,0.012901,-0.012901,...,-0.030654,-0.014788,0.041624,-0.026358,0.009413,-0.009413,0.018683,-0.018683,0.025569,-0.025569
Exercise_Frequency_Rarely,0.007011,0.038155,-0.021551,0.009795,0.035495,0.060458,-0.005769,-0.054595,0.002051,-0.002051,...,0.018595,-0.028932,0.001411,0.028009,0.015666,-0.015666,0.036016,-0.036016,-0.004175,0.004175
Blood_Pressure_High,-0.001207,0.009275,-0.001770,0.043696,0.033188,0.047372,-0.066047,0.019744,-0.018590,0.018590,...,-0.004812,-0.029449,0.040906,-0.010739,-0.010640,0.010640,0.004354,-0.004354,-0.000518,0.000518
Blood_Pressure_Low,-0.063498,0.001674,0.004255,-0.051179,0.032471,-0.002421,0.009209,-0.006937,0.052061,-0.052061,...,-0.006842,-0.035202,0.009723,0.026119,-0.017578,0.017578,-0.031248,0.031248,0.023886,-0.023886
Blood_Pressure_Normal,0.063970,-0.010653,-0.002491,0.008227,-0.064309,-0.043561,0.054964,-0.012293,-0.033454,0.033454,...,0.011435,0.063383,-0.049298,-0.015413,0.027707,-0.027707,0.026681,-0.026681,-0.023120,0.023120
Cholesterol_Level_Borderline,0.006529,-0.005710,0.020751,0.011283,-0.009635,-0.062328,0.060626,0.000721,-0.024417,0.024417,...,-0.482212,0.007342,0.021975,-0.029317,-0.043818,0.043818,0.015038,-0.015038,-0.005912,0.005912
Cholesterol_Level_High,-0.078438,0.046332,0.030364,0.016381,-0.017271,0.023390,-0.028417,0.005487,0.048562,-0.048562,...,-0.491918,-0.006589,-0.009118,0.015765,0.050760,-0.050760,-0.059126,0.059126,0.029419,-0.029419
Cholesterol_Level_Normal,0.074086,-0.041864,-0.052501,-0.028413,0.027645,0.039699,-0.032780,-0.006388,-0.025018,0.025018,...,1.000000,-0.000729,-0.013100,0.013767,-0.007427,0.007427,0.045493,-0.045493,-0.024243,0.024243
Stress_Level_High,0.037969,0.009936,0.010243,-0.056056,0.039585,-0.055541,0.047733,0.007035,-0.018729,0.018729,...,-0.000729,1.000000,-0.505649,-0.513787,-0.046163,0.046163,0.079172,-0.079172,0.029297,-0.029297
Stress_Level_Low,-0.061615,-0.006439,0.023344,0.007951,-0.019499,-0.012091,0.023797,-0.012091,0.004471,-0.004471,...,-0.013100,-0.505649,1.000000,-0.480363,0.011625,-0.011625,-0.071304,0.071304,-0.020181,0.020181
Stress_Level_Medium,0.022671,-0.003698,-0.033627,0.049081,-0.020853,0.068487,-0.072190,0.004871,0.014595,-0.014595,...,0.013767,-0.513787,-0.480363,1.000000,0.035370,-0.035370,-0.009581,0.009581,-0.009715,0.009715
Medication_Use_Occasional,-0.004904,-0.026235,0.018838,0.040871,0.030070,0.018728,-0.005084,-0.013561,-0.016139,0.016139,...,-0.007427,-0.046163,0.011625,0.035370,1.000000,-1.000000,-0.030459,0.030459,-0.038495,0.038495
Medication_Use_Regular,0.004904,0.026235,-0.018838,-0.040871,-0.030070,-0.018728,0.005084,0.013561,0.016139,-0.016139,...,0.007427,0.046163,-0.011625,-0.035370,-1.000000,1.000000,0.030459,-0.030459,0.038495,-0.038495
Family_History_No,0.042897,-0.037204,-0.044911,0.036391,0.034868,0.046036,0.018618,-0.064955,-0.015104,0.015104,...,0.045493,0.079172,-0.071304,-0.009581,-0.030459,0.030459,1.000000,-1.000000,0.035385,-0.035385
Family_History_Yes,-0.042897,0.037204,0.044911,-0.036391,-0.034868,-0.046036,-0.018618,0.064955,0.015104,-0.015104,...,-0.045493,-0.079172,0.071304,0.009581,0.030459,-0.030459,-1.000000,1.000000,-0.035385,0.035385
Illness_No,-0.022039,-0.046642,-0.039390,-0.005268,-0.021042,-0.035250,-0.023014,0.058636,-0.026701,0.026701,...,-0.024243,0.029297,-0.020181,-0.009715,-0.038495,0.038495,0.035385,-0.035385,1.000000,-1.000000
Illness_Yes,0.022039,0.046642,0.039390,0.005268,0.021042,0.035250,0.023014,-0.058636,0.026701,-0.026701,...,0.024243,-0.029297,0.020181,0.009715,0.038495,-0.038495,-0.035385,0.035385,-1.000000,1.000000